baseurl = "https://ineszz.rbind.io/"
title = "Statisticile lui Ines"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-138947404-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# enable emoji
enableEmoji = true
[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "<Numbers have an important story to tell. However, they rely on you to give them a clear and convincing voice.> ~ Stephen Few"
  copyright = "&copy;2020 ineszz"
  sidebarAbout = [
    "Un blog in romana & engleza.",
    "Sunt entuziasmata de date, inovatie si tehnologie.",
    "Scriu despre R si alte tehnologii. Pareri personale.",
    "Locatie: Bucuresti." 
    ]

# Rules to generate permanent links of your pages
[permalinks]
    blog = "/:section/:year/:month/:day/:slug"
    
  # Nav links in the side bar
  [[params.navlinks]]  
  name = "Home"
  url = "blog/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"


  [params.social]
#  email         = "email@example.com"
  twitter       = "https://twitter.com/inesz"
  linkedin      = "https://www.linkedin.com/in/inesteaca/"
  github        = "https://github.com/ineszz"