baseurl = "https://ineszz.rbind.io/"
title = "Statisticile lui Ines"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-138947404-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "<Numbers have an important story to tell. However, they rely on you to give them a clear and convincing voice.> ~ Stephen Few"
  copyright = "&copy;2020 ineszz"
  sidebarAbout = [
    "Entuziasmata de date si tehnologie, curiosa si optimista. ",
    "Scriu despre R si alte tehnologii.",
    "Pareri personale.",
    "Locatie: Bucuresti." 
    ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "post/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
#  email         = "email@example.com"
  twitter       = "https://twitter.com/inesz"
  linkedin      = "https://www.linkedin.com/in/inesteaca/"
  github        = "https://github.com/ineszz"